name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev libreadline6-dev libssl-dev zlib1g-dev openjdk-17-jdk python3-pip unzip

      - name: Install Buildozer and Cython
        run: |
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d /tmp/cmdline-tools
          mkdir -p /home/runner/android-sdk
          mv /tmp/cmdline-tools/cmdline-tools /home/runner/android-sdk/latest
          export ANDROID_HOME=/home/runner/android-sdk
          export PATH=$PATH:$ANDROID_HOME/latest/bin
          yes | /home/runner/android-sdk/latest/bin/sdkmanager --licenses
          /home/runner/android-sdk/latest/bin/sdkmanager "build-tools;33.0.2" "platforms;android-33" "platform-tools"
        env:
          ANDROID_HOME: /home/runner/android-sdk

      - name: Set up Buildozer environment
        run: |
          echo "export ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$PATH:/home/runner/android-sdk/latest/bin:/home/runner/android-sdk/platform-tools" >> $GITHUB_ENV

      - name: Build APK
        run: |
          buildozer android release
        working-directory: ./

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: ./bin/*.apk
          retention-days: 5
