name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev libncursesw5-dev libreadline6-dev libssl-dev zlib1g-dev openjdk-17-jdk python3-pip
          pip install buildozer cython

      - name: Install Android SDK and NDK
        run: |
          buildozer android debug
        working-directory: ./
        continue-on-error: true # Permite continuar mesmo se o build falhar (para baixar SDK/NDK)

      - name: Build APK
        run: |
          buildozer android release
        working-directory: ./

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: ./bin/*.apk
          retention-days: 5
